app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.cache import cache_page
from django.conf.urls.static import static
from pwa import views as pwa_views
from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('chat/', include('chat.urls'))
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path, include
from rest_framework import routers

from carts import views

app_name = 'carts'
router = routers.DefaultRouter()
router.register(r'carts', views.MobileCartsApi)


urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
    path('api/', include(router.urls)),
]

goods/urls.py
from django.urls import path, include
from rest_framework import routers

from goods import views

app_name = 'goods'
router = routers.DefaultRouter()
router.register(r'cat', views.MobileCategoryApi)
router.register(r'products', views.ProductsCategoryApi)

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),

    path('categories/', views.categories, name='categories'),
    path('categories/<slug:category_slug>/', views.subcategories, name='subcategories'),

    path('main/categories-main/', views.categories_list, name='categories-main'),  # Updated view function name
    path('main/categories-main/<slug:category_slug>/', views.subcategories_list, name='subcategories-main'),
    path('main/categories-main/<slug:category_slug>/<slug:subcategory_slug>/', views.products_by_subcategory, name='products_by_subcategory'),

    # Updated view function name

    path('api/', include(router.urls)),
]

goods/models.py
from django.db import models
from django.urls import reverse


class Categories(models.Model):
    """ Каталог """
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class SubCategories(models.Model):
    """ Под Категория"""
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, related_name='sub_categoriess')

    class Meta:
        db_table = 'subcategory'
        verbose_name = 'Под Категорию'
        verbose_name_plural = 'Под Категории'

    def __str__(self):
        return self.name


class Products(models.Model):
    """Продукты """
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')
    sub_category = models.ForeignKey(to=SubCategories, on_delete=models.CASCADE, related_name='sub_categories',
                                     default=1)

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ("name",)

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'

    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})

    def display_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price*self.discount/100, 2)
        
        return self.price

goods/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_list_or_404, get_object_or_404, render
from rest_framework import viewsets
from django.contrib.postgres.search import TrigramSimilarity

from goods.models import Products, Categories, SubCategories
from goods.utils import q_search
from goods.serializers import CategoriesSerializer, ProductsSerializer



def q_search(query):
    query = query.lower()
    return Products.objects.filter(Q(name__icontains=query))


def catalog(request, category_slug=None):
    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    if category_slug == "all":
        goods = Products.objects.all()
    elif query:
        goods = q_search(query)
    else:
        goods = Products.objects.filter(category__slug=category_slug)

    if on_sale:
        goods = goods.filter(discount__gt=0)

    if order_by and order_by != "default":
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, 6)
    current_page = paginator.page(int(page))

    context = {
        "title": "Главная страница - Каталог",
        "goods": current_page,
        "slug_url": category_slug
    }
    return render(request, "goods/catalog.html", context)


def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)
    context = {"product": product}
    return render(request, "goods/product.html", context=context)


def categories(request):
    # Получаем все категории и их подкатегории
    categories = Categories.objects.all()
    subcategories = SubCategories.objects.all()
    return render(request, 'goods/category.html', {
        'categories': categories,
        'subcategories': subcategories,
    })


def subcategories(request, category_slug):
    # Получаем категорию по slug
    category = get_object_or_404(Categories, slug=category_slug)
    subcategories = SubCategories.objects.filter(category=category)
    return render(request, 'goods/subcategory.html', {'category': category, 'subcategories': subcategories})


def products(request, category_slug, subcategory_slug=None):
    # Получаем категорию по slug
    category = get_object_or_404(Categories, slug=category_slug)
    if subcategory_slug:
        # Если указана подкатегория, получаем ее
        subcategory = get_object_or_404(SubCategories, slug=subcategory_slug)
        # Получаем товары для указанной подкатегории
        products = Products.objects.filter(category=category, sub_category=subcategory)
    else:
        # Если не указана подкатегория, получаем все товары для категории
        products = Products.objects.filter(category=category)
        subcategory = None
    return render(request, 'goods/product-2.html', {'category': category, 'subcategory': subcategory, 'products': products})


def products_by_subcategory(request, category_slug, subcategory_slug):
    # Получаем подкатегорию
    subcategory = SubCategories.objects.get(slug=subcategory_slug)

    # Получаем все товары для данной подкатегории, отсортированные по главной категории, а затем по подкатегории
    products = Products.objects.filter(category__slug=category_slug, sub_category__slug=subcategory_slug)

    context = {
        'subcategory': subcategory,
        'products': products
    }
    return render(request, 'goods/sub-products.html', context)

#======================categories============================

def categories_list(request):
    categories = Categories.objects.all()
    return render(request, 'goods/main-categories.html', {'categories': categories})


def subcategories_list(request, category_slug):
    category = Categories.objects.get(slug=category_slug)
    subcategories = SubCategories.objects.filter(category=category)
    products = Products.objects.filter(category=category)
    if subcategories:
        return render(request, 'goods/main-subcategories.html', {'category': category, 'subcategories': subcategories})
    else:
        # здесь предполагается логика вывода продуктов, связанных с основной категорией
        return render(request, 'goods/main-products.html', {
                                        'category': category,
                                        'products': products,

                                                            })

#====================mobile-api==============================


class MobileCategoryApi(viewsets.ModelViewSet):
    queryset = Categories.objects.all()
    serializer_class = CategoriesSerializer


class ProductsCategoryApi(viewsets.ModelViewSet):
    queryset = Products.objects.all()
    serializer_class = ProductsSerializer

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}


{% block content %}
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
<div class="row">
    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фильтры
        </button>

        <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}
                <label class="form-check-label" for="flexCheckDefault">
                    Товары по акции
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>

    {% if request.GET.q %}
    <h3 class="mt-4">Результаты поиска по запросу {{ request.GET.q }}</h3>
    {% if not goods %}
        <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
        <h2 class="mt-4">По запросу ничего не найдено</h2>
    {% endif %}
    {% endif %}
    {% for product in goods %}
        <!-- Карта товара -->
        <div class="col-lg-4 col-md-6 p-4">
            <div class="card border-primary rounded custom-shadow">
                {% if product.image %}
                    <a href="{% url "catalog:product" product.slug %}" ><img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" width="600" height="300"></a>
                {% else %}
                    <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <a href="{% url "catalog:product" product.slug %}">
                        <p class="card-title">
                            {% autoescape off %}
                                {% if product.headline %}
                                {{product.headline}}
                                {% else %}
                                {{ product.name }}
                                {% endif %}
                            {% endautoescape %}
                        </p>
                    </a>
                    <p class="card-text">
                        {% autoescape off %}
                            {% if product.bodyline %}
                            {{product.bodyline|truncatechars:100}}
                            {% else %}
                            {{ product.description|truncatechars:35 }}
                            {% endif %}
                        {% endautoescape %}
                    </p>
                    <p class="product_id">Количество товара: {{ product.quantity }}</p>
                    <div class="d-flex justify-content-between">

                        {% if product.quantity > 0 %}
                            {% if product.discount %}
                                <p><s>{{ product.price }}</s> ₸</p>
                                <p><strong>{{ product.sell_price }} ₸</strong></p>
                                <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                            {% else %}
                                <p><strong>{{ product.price }} ₸</strong></p>
                            {% endif %}

                            <a href="{% url "cart:cart_add" %}" class="btn add-to-cart"
                               data-product-id="{{ product.id }}">
                                {% csrf_token %}
                                <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                                     width="32" height="32">
                            </a>
                        {% else %}
                            {% if product.discount %}
                                <p><s>{{ product.price }}</s> ₸</p>
                                <p><strong>{{ product.sell_price }} ₸</strong></p>
                                <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                            {% else %}
                                <p><strong>{{ product.price }} ₸</strong></p>
                            {% endif %}
                            <p>Товара нет в наличии</p>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
    {% endfor %}


</div>
<!-- Пагинация -->
{% if goods %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">

                <li class="page-item {% if not goods.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="{% if goods.has_previous %}?{% change_params page=goods.previous_page_number %}{% else %}#{% endif %}">Назад</a>
                </li>

                {% for page in goods.paginator.page_range %}
                    {% if page >= goods.number|add:-4 and page <= goods.number|add:4 %}
                        <li class="page-item {% if goods.number == page %} active {% endif %}">
                            <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item {% if not goods.has_next %}disabled{% endif %}">
                    <a class="page-link" href="{% if goods.has_next %}?{% change_params page=goods.next_page_number %}{% else %}#{% endif %}">Следующая</a>
                </li>
            </div>
        </ul>
    </nav>
{% endif %}

{% endblock  %}

goods/templates/goods/main-categories.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Все категорий</title>
    <link rel="stylesheet" href="{% static "deps/css/category.css" %}">

</head>
<body>
    <div class="cards-container">
        {% for category in categories %}
        <div class="card">
            <img src="{{ category.image.url }}" alt="{{ category.name }}">
            <div class="card-content">
                <a href="{{ category.slug }}">{{ category.name }}</a>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}

goods/templates/goods/main-products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Products</title>
</head>
<body>
    <h1>Products in {{ category.name }}</h1>
    {{ category.slug }}
    <p>Display products related to the main category here...</p>
        {{ category.products.name }}
        {{ products.image }}

{% for product in goods %}
        <!-- Карта товара -->
        <div class="col-lg-4 col-md-6 p-4">
            <div class="card border-primary rounded custom-shadow">
                {% if product.image %}
                    <a href="{% url "catalog:product" product.slug %}" ><img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" width="600" height="300"></a>
                {% else %}
                    <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <a href="{% url "catalog:product" product.slug %}">
                        <p class="card-title">
                            {% autoescape off %}
                                {% if product.headline %}
                                {{product.headline}}
                                {% else %}
                                {{ product.name }}
                                {% endif %}
                            {% endautoescape %}
                        </p>
                    </a>
                    <p class="card-text">
                        {% autoescape off %}
                            {% if product.bodyline %}
                            {{product.bodyline|truncatechars:100}}
                            {% else %}
                            {{ product.description|truncatechars:35 }}
                            {% endif %}
                        {% endautoescape %}
                    </p>
                    <p class="product_id">Количество товара: {{ product.quantity }}</p>
                    <div class="d-flex justify-content-between">

                        {% if product.quantity > 0 %}
                            {% if product.discount %}
                                <p><s>{{ product.price }}</s> ₸</p>
                                <p><strong>{{ product.sell_price }} ₸</strong></p>
                                <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                            {% else %}
                                <p><strong>{{ product.price }} ₸</strong></p>
                            {% endif %}

                            <a href="{% url "cart:cart_add" %}" class="btn add-to-cart"
                               data-product-id="{{ product.id }}">
                                {% csrf_token %}
                                <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                                     width="32" height="32">
                            </a>
                        {% else %}
                            {% if product.discount %}
                                <p><s>{{ product.price }}</s> ₸</p>
                                <p><strong>{{ product.sell_price }} ₸</strong></p>
                                <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                            {% else %}
                                <p><strong>{{ product.price }} ₸</strong></p>
                            {% endif %}
                            <p>Товара нет в наличии</p>
                        {% endif %}

                    </div>

                </div>
            </div>
        </div>
</body>
</html>

goods/templates/goods/main-subcategories.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Все категорий</title>
    <link rel="stylesheet" href="{% static "deps/css/category.css" %}">
</head>
<body>
    <div class="cards-container">
        {% for subcategory in subcategories %}
        <div class="card">
            <img src="{{ subcategory.image.url }}" alt="{{ subcategory.name }}">
            <div class="card-content">
                <a href="{{ subcategory.slug }}">{{ subcategory.name }}</a>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock  %}

{% block content %}
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры продуктов -->
            <div class="col-md-4">
                <img src="{{ product.image.url }}" class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>
            <div class="col-md-8">
                <!-- Описание продукта -->
                <div class="card-body">
                    <h4 class="card-title">{{ product.name }}</h4>
                    <p class="card-text text-justify">{{ product.description }}</p>
                </div>

                <!-- Наличие и количество товара -->
                <div class="card-body">
                    {% if product.quantity == 0 %}
                        <p class="product_not_available" style="color: red;">
                            <img src="https://cstor.nn2.ru/forum/data/forum/images/2019-02/225811965-ozidaetsj_postavka.png" alt="Not Available">
                            Товара нет в наличии
                        </p>
                    {% else %}
                        <p class="product_id">Количество товара: {{ product.quantity }} штук</p>
                    {% endif %}
                </div>
            </div>

            <!-- Режим для увеличенного изображения -->
            <div class="modal fade" id="imageModal1" tabindex="-1" aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">Название товара: {{ product.name }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            <img src="{{ product.image.url }}" class="img-fluid" alt="Изображение 1">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Цена и добавить в корзину -->
        <div class="card-body">
            {% if product.quantity > 0 %}
                <p class="card-text">Цена: <strong>{{ product.sell_price }} ₸</strong></p>
                <a href="{% url 'cart:cart_add' %}" class="btn btn-dark add-to-cart" data-product-id="{{ product.id }}">
                    {% csrf_token %}
                    Добавить в корзину
                </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

goods/templates/goods/sub-products.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
{% block content %}
{% block css %}
{% endblock %}

<link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
<body>
    <h1>Products for Subcategory: {{ subcategory.name }}</h1>
    <div class="card-container">
        {% for product in products %}
        <div class="card">
            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
            <div class="card-body">
                <h5 class="product_id">{{ product.name }}</h5>
                <p>{{ product.price }}</p>
                {{ 'product.image.url' }}
                <span class="badge bg-warning text-dark">New</span>
                <span class="badge badge-banner">Special Offer</span>
                <a href="{% url 'goods:product' product_slug=product.slug %}">Ссылка</a>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}